server:
  port: 8083
spring:
  application:
    name: customers-service
  cloud:
    consul:
      port: ${CONSUL_PORT:8500}
      host: ${CONSUL_HOST:localhost}
  data:
    mongodb:
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}
  config:
    import: optional:configserver:http://${HOST_NAME:localhost}:${SPRING_CONFIG_PORT:8888}
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://${KC_HOST:keycloak}:${KC_PORT:8080}/auth/realms/rental_cars
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER:http://localhost:9411/}

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


springdoc:
  version: '@springdoc.version@'