
server:
  port: 8085
spring:
  application:
    name: consul-config-service
  cloud:
    vault:
      kv:
        enabled: true
      scheme: http
      token: root
    consul:
      discovery:
        register: true
      port: ${CONSUL_PORT:8500}
      host: ${CONSUL_HOST:localhost}
  config:
    import: 'optional:consul:, vault:// '

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER:http://localhost:9411/}

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

