spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: system
    password: tiger
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
