management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
resilience4j:
  circuit breaker:
    instances:
      customers-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 9
        slidingWindowType: COUNT_BASED

  #this fields for @Retry
  retry:
    instances:
      customers-service:
        waitDuration: 10s
        max-attempts: 6
      cars-service:
        waitDuration: 10s
        max-attempts: 10
  #this one if I use @RateLimiter
#  rate-limiter:
#    instances:
#      customers-service:
#        register-health-indicator: false
#        limit-for-period: 10
#        limit-refresh-period: 10s
#        timeout-duration: 3s
